### PR TITLE
event section added

### PR DESCRIPTION
**Pull request by Shrishti20706**
please check the event section added by me and merge it.

### CODE REVIEW

**Comment by ayushnandanwar** [comment]
Hey @Shrishti20706 , You might be 1 commit behind to this branch,
and Please see given UI in images folder or [Click here for UI](https://github.com/ayushnandanwar08/ecell-website/blob/master/images/UI.png) and do work as per UI only. I appreciated your work. Please make changes according to UI and you are welcome

Than you 
E-Cell MITAOE
GDSC MITAOE

**Review by ayushnandanwar — COMMENTED** [review]
Please do work as per the instruction given in md file

**Review by ayushnandanwar — CHANGES_REQUESTED** [review]
Please do work as per given UI

**Comment by Shrishti20706** [comment]
Ok I will try.

**Pull request closed without merging**
